### ISSUE TITLE
chapter 7 simple dictionary are not written like that anymore

### ISSUE THREAD

**Issue by Lyrian202** [talkpython/python-for-absolute-beginners-course#12]
i have followed the chapter 7 code coping perfectly what you do in the videos yet python doesn't seem to accept that anymore. i am using python 8

**Comment by mikeckennedy** [comment]
Hi Lyrian, you'll have to give me an example. This code is written on the very latest Python language version and did work when I wrote it.

**Comment by Lyrian202** [comment]
this is my code and the context action tells me that i can convert it to a dict litiral to a dict constructed
rolls = {
    'rock' = {
        'defeats': ['scissors'],
        'defeated_by': ['paper']
    }
    'paper': {
        'defeats': ['rock'],
        'defeated_by': ['scissors']
    },

    'scissors': {
        'defeats': ['paper'],
        'defeated_by': ['rock']
    },

**Comment by mikeckennedy** [comment]
You're missing a comma between these two parts

}
'paper': {
