### ISSUE TITLE
Add Sorting Algorithms

### ISSUE THREAD

**Issue by arifamd00** [talkpython/python-for-absolute-beginners-course#16]
Write clean and clear data of all sorting algorithms as they are very important when it comes to optimizing the data.

**Comment by HarshKumarSingh07** [comment]
Is this issue still there, being beginner I would like to contribute to it

**Comment by mikeckennedy** [comment]
No. @HarshKumarSingh07 Check out https://awesome-python.com/ find a project you like, look in their github project for "good first issue" issues to help out.

**Comment by ImYourDaddyListen2Me** [comment]
Ok, I don’t remember what I asked you. And things here right now are just a bit weird. I’ll need a laptop or desktop for most or all of the projects or does iPhones, 10, 11 pro and a 11pro max work? 


Sent from The Desk of Won’t order off the Home Depot app anymore!


On Wednesday, April 7, 2021, 1:45 PM, Michael Kennedy ***@***.***> wrote:




No. @HarshKumarSingh07 Check out https://awesome-python.com/ find a project you like, look in their github project for "good first issue" issues to help out.

**Comment by mikeckennedy** [comment]
You can the Pythonista app for much but not all of the exercises I think. I don't know how you get the code from here to there however. Copy from the github page maybe.
