### ISSUE TITLE
Ch06 question

### ISSUE THREAD

**Issue by Morantz** [talkpython/python-for-absolute-beginners-course#2]
Should I be separating this exercise into more functions:

My code is at :  https://github.com/Morantz/python-for-absolute-beginners-course/blob/master/practices/ch06-organizing-code-with-functions/guessingfunctions.py

Thanks!
Dan

**Comment by mikeckennedy** [comment]
Looks about right to me! I just added solutions here:

https://github.com/talkpython/python-for-absolute-beginners-course/tree/master/solutions

You can compare and see but they are similar. Well done.
