### ISSUE TITLE
Ch10 - Issue using prompt_toolkit

### ISSUE THREAD

**Issue by Niobel** [talkpython/python-for-absolute-beginners-course#26]
I was trying to use the prompt_toolkit thing and the program crushed, here's the error that pycharm shows:
"ModuleNotFoundError: No module named 'prompt_toolkit'"

It gives me the feeling that this is a trifle, and even so I haven't been able to fix it. Thank you in advance.

**Comment by Niobel** [comment]
By the way this course is super great! I'm learning a lot and understanding everything, even though that my english is not the best. Thank you for making it!

**Comment by mikeckennedy** [comment]
Hi @Niobel Glad you're enjoying the course! Have you installed prompt_toolkit into your active environment? Try:

```
C:\> pip list
```

If you don't see prompt_toolkit in the list, that's the problem. Fix it with 

```
C:\> pip install prompt_toolkit
```

**Comment by mikeckennedy** [comment]
I'm going to close this since I haven't heard back and I think this is the right fix. Reopen it if it's not the right fix.
