### ISSUE TITLE
Invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by Flopsdotgov** [talkpython/python-for-absolute-beginners-course#35]
There's a very real chance I'm doing something wrong here so forgive me. After copying the code from 

python-for-absolute-beginners-course/code/06-organizing-code-with-functions/rocks-game/rpsgame.py

the program runs the header, lists available rolls, then requests a roll. after submitting a roll I ge thit with this error: 
![Screenshot 2021-04-15 113029](https://user-images.githubusercontent.com/82549612/114905301-6b187e80-9dde-11eb-92f2-c92b75916ad5.png)

apologies if I'm missing something obvious, much appreciated.

**Comment by mikeckennedy** [comment]
Hi @Flopsdotgov The problem is this line:

```
selected_index = int(text)
```

You need to answer the question with 1, 2, 3, etc. not the value but the position. You can (and I think we do later) answer in words like rock or paper, but then you need to use a different why to find the selected play using names in some look up.
