### ISSUE TITLE
Ch 6 - Cleaning up with functions question

### ISSUE THREAD

**Issue by pedrogmas** [talkpython/python-for-absolute-beginners-course#36]
Hi Michael and everybody. This might be a pointless question but when introducing functions into our more "rudimentary" code and defining them, I see you "take in" (not sure what you mean by that) player_1 and player_2 into the "play_game" function. So:
def play_game(player_1, player_2):
I'm guessing this is because the function will need these two variables. But I don't understand why then, when defining the main() function at the top we change the names of these variables in the play_game function. "(player, ai)"
And furthermore, now that we have changed them we don't have to go back down to the defining play_game lines to change (player_1, player_2) into (player, ai)
To make the question simple I just don't understand why we needed to change these variables names only at the top when defining the main() function but leaving different variable names when defining the play_game function.

Thank you very much for your time!

**Comment by mikeckennedy** [comment]
Hi @pedrogmas good question.  This is actually a really important concept of separation of concerns and reusability. 

At the function level:

```python
def play_game(player1, player2):
   # details on playing the game...
```

We want to think of two abstract players. This could two human players or it could a human player and an AI player. 

But when we use it, we're working with a specific situation:

```python
play_game("Michael", "Computer")
```

I do think we broke this a little when we added the random computer rolls to the play game method. But if we had kept going, it would have allowed us to provide two players objects, each knowing how to get a roll. The human version, it would use `input()` and the computer version would use `random` but the play_game method wouldn't know which is which. 

That example was a bit complicated for the topics of the course so we landing in a weird middle ground.

**Comment by pedrogmas** [comment]
Hi Michael. Thank you for your reply. I see. When defining the function you think of two general player, as we might want to use the function in more specific cases. I getit. Thank you!

**Comment by ImYourDaddyListen2Me** [comment]
I think you sent your email to the wrong person. I’m not Michael.


Sent from The Desk of Won’t order off the Home Depot app anymore!


On Sunday, July 11, 2021, 9:59 AM, pedrogmas ***@***.***> wrote:




Hi Michael. Thank you for your reply. I see. When defining the function you think of two general player, as we might want to use the function in more specific cases. I getit. Thank you!

**Comment by mikeckennedy** [comment]
It's just github notifications for all interested in this thread. You're welcome @pedrogmas  . :)
