### ISSUE TITLE
Problem with functions

### ISSUE THREAD

**Issue by Wolf-Quest** [talkpython/python-for-absolute-beginners-course#38]
![image](https://user-images.githubusercontent.com/103428812/165993085-fe4b361f-058f-4ae3-85ac-4af9d2e85660.png)
![image](https://user-images.githubusercontent.com/103428812/165993155-49347742-f7c9-40bb-b86c-2ac2047520fa.png)
![image](https://user-images.githubusercontent.com/103428812/165993224-22ec3507-e910-404b-815a-cc9fcf96a770.png)
![image](https://user-images.githubusercontent.com/103428812/165993343-5dabef0c-f324-465e-8e2e-038b2ef51fef.png)

I'm not really sure how to use functions and what the functions' brackets do. My code was working perfectly before I started adding functions and then I tried following what the errors told me, but it's not working for me. Can someone please tell me what I have to do?

**Comment by mikeckennedy** [comment]
Hi. Can you share a smaller section of code that is the issue or maybe the entire file as text rather than an image? Then I might have a better idea what's up.

**Comment by Wolf-Quest** [comment]
I've pasted the code onto the notepad because it wouldn't accept a python file.
Also, there may be a few problems because I have tried fixing it myself.

[PythonRPS.txt](https://github.com/talkpython/python-for-absolute-beginners-course/files/8647455/PythonRPS.txt)

**Comment by mikeckennedy** [comment]
Glad you got it fixed wolf.

**Comment by Wolf-Quest** [comment]
I fixed it by re-watching the chapter. Thank you.

**Comment by Wolf-Quest** [comment]
I fixed it by re-watching the chapter to help me understand it. Thank you.
