### ISSUE TITLE
Rock_Paper_Scissors player1 v player_1

### ISSUE THREAD

**Issue by wmdaniel** [talkpython/python-for-absolute-beginners-course#6]
In Ch 9 rpsgame.py, you use the variable "player1" in the main function, but everywhere else you use the variable "player_1". What's going on here? Your code works in the tutorial, but I'm unable to follow why. I'm also wondering if it's good practice to use both variables.

Thanks for your time,
Daniel

**Comment by mikeckennedy** [comment]
Hi,

I think what's happen is that you are seeing a variable name in one place and it being used in a function later. Functions get to decide what their inputs (parameters) are called regardless of what's passed to them:

```python
# Variable usage
def main():
    ...
    player1, player2 = get_players()
    log(f"{player1} has logged in.")
    play_game(player1, player2)
```

```python
# Function call, first time with the same name as the variables
def play_game(player_1, player_2):
    log(f"New game starting between {player_1} and {player_2}.")

    wins = {player_1: 0, player_2: 0}
    roll_names = list(rolls.keys())
   ...
```
```python
# Another function call, this time with a different parameter name
# Some times player_name == player1 other times, player_name == player2
def get_roll(player_name, roll_names):
    print("Available rolls:")
    for index, r in enumerate(roll_names, start=1):
        print(f"{index}. {r}")

    text = input(f"{player_name}, what is your roll? ")
```
