### ISSUE TITLE
Color Labels

### ISSUE THREAD

**Issue by Anduie** [talkpython/python-for-absolute-beginners-course#7]
I am not able to get the virtual environment (neither in CMD or in the terminal) to interpret colors. What I'm getting is the ANSI escape codes instead of the actual colors.

Looking at StackOverflow, you'll need to also import init in colorama and add init(convert=True).

I just figured that out, but you may want to consider altering some the lectures. Or I totally missed it.

**Comment by mikeckennedy** [comment]
Hi @Anduie 

Thanks for the heads up here. This all depends on how you have Windows setup and the terminal people are using. Have a look here:

![colors](https://user-images.githubusercontent.com/2035561/88578779-ee4e3600-cffd-11ea-9031-43171549cc78.PNG)

I recommend everyone on Windows switch to the new Terminal. See the video here:

https://www.youtube.com/watch?v=8gw0rXPMMPE

And you can get it in the Windows Store:

https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab

But I have also fixed the code to work on `cmd.exe` by adding this at the top (test so it doesn't break other systems):

```python
if platform.system() == 'Windows':
        colorama.init(convert=True)
```

Thanks.
