### ISSUE TITLE
CH 6. Adding the best-of feature

### ISSUE THREAD

**Issue by NeaMitika** [talkpython/python-for-absolute-beginners-course#8]
This lesson was a MESS.... i couldnt understand S***... you go so fast on everything.... 

You select, copy, paste, write so fast... i had to watch it  3 times and i still cand keep it up.

Thumb down!

**Comment by mikeckennedy** [comment]
Sorry you didn't like it. FWIW, you can slow down the player as well as use hotkeys to jump back 10 sec or pause it. We also have the solutions and code available here.
